pages:
  stage: deploy
#  tags: [node]
  only:
    - master
  environment:
    name: master
  script:
    - npm install
    - npm run build
    # Выкладка
    - ls -la
    - mv dist public
  artifacts:
    expire_in: 15 mins
    paths:
    - public